// <auto-generated />
using System;
using ERP_System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP_System.Migrations
{
    [DbContext(typeof(Application_Identity_DbContext))]
    [Migration("20211105191605_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP_System.Models.HR.UsersAccounts.Employee_UserAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("adddate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ConsumeUnit", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<double>("Factor")
                        .HasColumnType("float");

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Materials_ConsumeUnit_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.Equivalence_Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("Equivalence_Group");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultConsumeUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("TypeID");

                    b.ToTable("Materials_Item_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemCommonSellPrice", b =>
                {
                    b.Property<long?>("ConsumeUnit_ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("SellType_SellTypeID")
                        .HasColumnType("bigint");

                    b.Property<long?>("_TradeStateTradeStateID")
                        .HasColumnType("bigint");

                    b.HasIndex("ConsumeUnit_ID");

                    b.HasIndex("Item_ID");

                    b.HasIndex("SellType_SellTypeID");

                    b.HasIndex("_TradeStateTradeStateID");

                    b.ToTable("Materials_ItemCommonSellPrice_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemFile", b =>
                {
                    b.Property<long>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.HasKey("FileID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Materials_ItemFile_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemRelation", b =>
                {
                    b.Property<int?>("AnotherItemID")
                        .HasColumnType("int");

                    b.Property<bool>("Inherit")
                        .HasColumnType("bit");

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Relation_")
                        .HasColumnType("bigint");

                    b.HasIndex("AnotherItemID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Materials_ItemRelation_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec", b =>
                {
                    b.Property<long>("SpecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<long>("SpecIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("SpecID");

                    b.HasIndex("TypeID");

                    b.ToTable("Materials_ItemSpec_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Restrict", b =>
                {
                    b.Property<long>("SpecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<long>("SpecIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SpecName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypeID")
                        .HasColumnType("bigint");

                    b.HasKey("SpecID");

                    b.HasIndex("TypeID");

                    b.ToTable("Materials_ItemSpec_Restrict_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Restrict_Options", b =>
                {
                    b.Property<long>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<long?>("ItemSpecRestrict_SpecID")
                        .HasColumnType("bigint");

                    b.Property<string>("OptionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OptionID");

                    b.HasIndex("ItemSpecRestrict_SpecID");

                    b.ToTable("Materials_ItemSpec_Restrict_Options_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Restrict_Value", b =>
                {
                    b.Property<long?>("ItemSpecRestrict_SpecID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ItemSpec_Restrict_Options_OptionID")
                        .HasColumnType("bigint");

                    b.Property<int?>("itemID")
                        .HasColumnType("int");

                    b.HasIndex("ItemSpecRestrict_SpecID");

                    b.HasIndex("ItemSpec_Restrict_Options_OptionID");

                    b.HasIndex("itemID");

                    b.ToTable("Materials_ItemSpec_Restrict_Value_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Value", b =>
                {
                    b.Property<long?>("ItemSpec_SpecID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Item_ID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ItemSpec_SpecID");

                    b.HasIndex("Item_ID");

                    b.ToTable("Materials_ItemSpec_Value_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultConsumeUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Materials_ItemCategory_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.Item_Equivalence_Relation", b =>
                {
                    b.Property<int?>("_Equivalence_GroupGroupID")
                        .HasColumnType("int");

                    b.Property<int?>("_ItemID")
                        .HasColumnType("int");

                    b.HasIndex("_Equivalence_GroupGroupID");

                    b.HasIndex("_ItemID");

                    b.ToTable("Materials_Item_Equivalence_Relation_Table");
                });

            modelBuilder.Entity("ERP_System.Models.Trade.SellType", b =>
                {
                    b.Property<long>("SellTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("SellTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SellTypeID");

                    b.ToTable("SellType");
                });

            modelBuilder.Entity("ERP_System.Models.Trade.TradeState", b =>
                {
                    b.Property<long>("TradeStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("TradeStateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TradeStateID");

                    b.ToTable("TradeState");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ConsumeUnit", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.Item", "Item_")
                        .WithMany()
                        .HasForeignKey("Item_ID");

                    b.Navigation("Item_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.Item", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ItemCategory", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemCommonSellPrice", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ConsumeUnit", "ConsumeUnit_")
                        .WithMany()
                        .HasForeignKey("ConsumeUnit_ID");

                    b.HasOne("ERP_System.Models.Materials.Item", "Item_")
                        .WithMany()
                        .HasForeignKey("Item_ID");

                    b.HasOne("ERP_System.Models.Trade.SellType", "SellType_")
                        .WithMany()
                        .HasForeignKey("SellType_SellTypeID");

                    b.HasOne("ERP_System.Models.Trade.TradeState", "_TradeState")
                        .WithMany()
                        .HasForeignKey("_TradeStateTradeStateID");

                    b.Navigation("_TradeState");

                    b.Navigation("ConsumeUnit_");

                    b.Navigation("Item_");

                    b.Navigation("SellType_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemFile", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.Item", "Item_")
                        .WithMany()
                        .HasForeignKey("Item_ID");

                    b.Navigation("Item_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemRelation", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.Item", "AnotherItem")
                        .WithMany()
                        .HasForeignKey("AnotherItemID");

                    b.HasOne("ERP_System.Models.Materials.Item", "Item_")
                        .WithMany()
                        .HasForeignKey("Item_ID");

                    b.Navigation("AnotherItem");

                    b.Navigation("Item_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ItemCategory", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Restrict", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ItemCategory", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Restrict_Options", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ItemSpec_Restrict", "ItemSpecRestrict_")
                        .WithMany()
                        .HasForeignKey("ItemSpecRestrict_SpecID");

                    b.Navigation("ItemSpecRestrict_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Restrict_Value", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ItemSpec_Restrict", "ItemSpecRestrict_")
                        .WithMany()
                        .HasForeignKey("ItemSpecRestrict_SpecID");

                    b.HasOne("ERP_System.Models.Materials.ItemSpec_Restrict_Options", "ItemSpec_Restrict_Options_")
                        .WithMany()
                        .HasForeignKey("ItemSpec_Restrict_Options_OptionID");

                    b.HasOne("ERP_System.Models.Materials.Item", "item")
                        .WithMany()
                        .HasForeignKey("itemID");

                    b.Navigation("item");

                    b.Navigation("ItemSpec_Restrict_Options_");

                    b.Navigation("ItemSpecRestrict_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.ItemSpec_Value", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.ItemSpec", "ItemSpec_")
                        .WithMany()
                        .HasForeignKey("ItemSpec_SpecID");

                    b.HasOne("ERP_System.Models.Materials.Item", "Item_")
                        .WithMany()
                        .HasForeignKey("Item_ID");

                    b.Navigation("Item_");

                    b.Navigation("ItemSpec_");
                });

            modelBuilder.Entity("ERP_System.Models.Materials.Item_Equivalence_Relation", b =>
                {
                    b.HasOne("ERP_System.Models.Materials.Equivalence_Group", "_Equivalence_Group")
                        .WithMany()
                        .HasForeignKey("_Equivalence_GroupGroupID");

                    b.HasOne("ERP_System.Models.Materials.Item", "_Item")
                        .WithMany()
                        .HasForeignKey("_ItemID");

                    b.Navigation("_Equivalence_Group");

                    b.Navigation("_Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERP_System.Models.HR.UsersAccounts.Employee_UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERP_System.Models.HR.UsersAccounts.Employee_UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.HR.UsersAccounts.Employee_UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERP_System.Models.HR.UsersAccounts.Employee_UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
